# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform AnonymousOverflow installation tasks
  when: anonymousoverflow_enabled | bool
  tags:
    - setup-all
    - setup-anonymousoverflow
    - install-all
    - install-anonymousoverflow
  block:
    - name: Validate AnonymousOverflow configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install AnonymousOverflow
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform AnonymousOverflow uninstallation tasks
  when: not anonymousoverflow_enabled | bool
  tags:
    - setup-all
    - setup-anonymousoverflow
  block:
    - name: Uninstall AnonymousOverflow
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
